"""Element/attribute id tables. GENERATED by scripts/gen_id_tables.py — do not edit."""

# Ghidra 12.2 vocabulary from ElementId.java / AttributeId.java

ELEM_DATA = 1  # data
ELEM_INPUT = 2  # input
ELEM_OFF = 3  # off
ELEM_OUTPUT = 4  # output
ELEM_RETURNADDRESS = 5  # returnaddress
ELEM_SYMBOL = 6  # symbol
ELEM_TARGET = 7  # target
ELEM_VAL = 8  # val
ELEM_VALUE = 9  # value
ELEM_VOID = 10  # void
ELEM_ADDR = 11  # addr
ELEM_RANGE = 12  # range
ELEM_RANGELIST = 13  # rangelist
ELEM_REGISTER = 14  # register
ELEM_SEQNUM = 15  # seqnum
ELEM_VARNODE = 16  # varnode
ELEM_BREAK = 17  # break
ELEM_CLANG_DOCUMENT = 18  # clang_document
ELEM_FUNCNAME = 19  # funcname
ELEM_FUNCPROTO = 20  # funcproto
ELEM_LABEL = 21  # label
ELEM_RETURN_TYPE = 22  # return_type
ELEM_STATEMENT = 23  # statement
ELEM_SYNTAX = 24  # syntax
ELEM_VARDECL = 25  # vardecl
ELEM_VARIABLE = 26  # variable
ELEM_OP = 27  # op
ELEM_SLEIGH = 28  # sleigh
ELEM_SPACE = 29  # space
ELEM_SPACEID = 30  # spaceid
ELEM_SPACES = 31  # spaces
ELEM_SPACE_BASE = 32  # space_base
ELEM_SPACE_OTHER = 33  # space_other
ELEM_SPACE_OVERLAY = 34  # space_overlay
ELEM_SPACE_UNIQUE = 35  # space_unique
ELEM_TRUNCATE_SPACE = 36  # truncate_space
ELEM_ABSOLUTE_MAX_ALIGNMENT = 37  # absolute_max_alignment
ELEM_BITFIELD_PACKING = 38  # bitfield_packing
ELEM_CHAR_SIZE = 39  # char_size
ELEM_CHAR_TYPE = 40  # char_type
ELEM_CORETYPES = 41  # coretypes
ELEM_DATA_ORGANIZATION = 42  # data_organization
ELEM_DEF = 43  # def
ELEM_DEFAULT_ALIGNMENT = 44  # default_alignment
ELEM_DEFAULT_POINTER_ALIGNMENT = 45  # default_pointer_alignment
ELEM_DOUBLE_SIZE = 46  # double_size
ELEM_ENTRY = 47  # entry
ELEM_ENUM = 48  # enum
ELEM_FIELD = 49  # field
ELEM_FLOAT_SIZE = 50  # float_size
ELEM_INTEGER_SIZE = 51  # integer_size
ELEM_LONG_DOUBLE_SIZE = 52  # long_double_size
ELEM_LONG_LONG_SIZE = 53  # long_long_size
ELEM_LONG_SIZE = 54  # long_size
ELEM_MACHINE_ALIGNMENT = 55  # machine_alignment
ELEM_POINTER_SHIFT = 56  # pointer_shift
ELEM_POINTER_SIZE = 57  # pointer_size
ELEM_SHORT_SIZE = 58  # short_size
ELEM_SIZE_ALIGNMENT_MAP = 59  # size_alignment_map
ELEM_TYPE = 60  # type
ELEM_TYPE_ALIGNMENT_ENABLED = 61  # type_alignment_enabled
ELEM_TYPEGRP = 62  # typegrp
ELEM_TYPEREF = 63  # typeref
ELEM_USE_MS_CONVENTION = 64  # use_MS_convention
ELEM_WCHAR_SIZE = 65  # wchar_size
ELEM_ZERO_LENGTH_BOUNDARY = 66  # zero_length_boundary
ELEM_BITFIELD = 289  # bitfield
ELEM_COLLISION = 67  # collision
ELEM_DB = 68  # db
ELEM_EQUATESYMBOL = 69  # equatesymbol
ELEM_EXTERNREFSYMBOL = 70  # externrefsymbol
ELEM_FACETSYMBOL = 71  # facetsymbol
ELEM_FUNCTIONSHELL = 72  # functionshell
ELEM_HASH = 73  # hash
ELEM_HOLE = 74  # hole
ELEM_LABELSYM = 75  # labelsym
ELEM_MAPSYM = 76  # mapsym
ELEM_PARENT = 77  # parent
ELEM_PROPERTY_CHANGEPOINT = 78  # property_changepoint
ELEM_RANGEEQUALSSYMBOLS = 79  # rangeequalssymbols
ELEM_SCOPE = 80  # scope
ELEM_SYMBOLLIST = 81  # symbollist
ELEM_HIGH = 82  # high
ELEM_BYTES = 83  # bytes
ELEM_STRING = 84  # string
ELEM_STRINGMANAGE = 85  # stringmanage
ELEM_COMMENT = 86  # comment
ELEM_COMMENTDB = 87  # commentdb
ELEM_TEXT = 88  # text
ELEM_ADDR_PCODE = 89  # addr_pcode
ELEM_BODY = 90  # body
ELEM_CALLFIXUP = 91  # callfixup
ELEM_CALLOTHERFIXUP = 92  # callotherfixup
ELEM_CASE_PCODE = 93  # case_pcode
ELEM_CONTEXT = 94  # context
ELEM_DEFAULT_PCODE = 95  # default_pcode
ELEM_INJECT = 96  # inject
ELEM_INJECTDEBUG = 97  # injectdebug
ELEM_INST = 98  # inst
ELEM_PAYLOAD = 99  # payload
ELEM_PCODE = 100  # pcode
ELEM_SIZE_PCODE = 101  # size_pcode
ELEM_BHEAD = 102  # bhead
ELEM_BLOCK = 103  # block
ELEM_BLOCKEDGE = 104  # blockedge
ELEM_EDGE = 105  # edge
ELEM_PARAMMEASURES = 106  # parammeasures
ELEM_PROTO = 107  # proto
ELEM_RANK = 108  # rank
ELEM_CONSTANTPOOL = 109  # constantpool
ELEM_CPOOLREC = 110  # cpoolrec
ELEM_REF = 111  # ref
ELEM_TOKEN = 112  # token
ELEM_IOP = 113  # iop
ELEM_UNIMPL = 114  # unimpl
ELEM_AST = 115  # ast
ELEM_FUNCTION = 116  # function
ELEM_HIGHLIST = 117  # highlist
ELEM_JUMPTABLELIST = 118  # jumptablelist
ELEM_VARNODES = 119  # varnodes
ELEM_CONTEXT_DATA = 120  # context_data
ELEM_CONTEXT_POINTS = 121  # context_points
ELEM_CONTEXT_POINTSET = 122  # context_pointset
ELEM_CONTEXT_SET = 123  # context_set
ELEM_SET = 124  # set
ELEM_TRACKED_POINTSET = 125  # tracked_pointset
ELEM_TRACKED_SET = 126  # tracked_set
ELEM_CONSTRESOLVE = 127  # constresolve
ELEM_JUMPASSIST = 128  # jumpassist
ELEM_SEGMENTOP = 129  # segmentop
ELEM_ADDRESS_SHIFT_AMOUNT = 130  # address_shift_amount
ELEM_AGGRESSIVETRIM = 131  # aggressivetrim
ELEM_COMPILER_SPEC = 132  # compiler_spec
ELEM_DATA_SPACE = 133  # data_space
ELEM_DEFAULT_MEMORY_BLOCKS = 134  # default_memory_blocks
ELEM_DEFAULT_PROTO = 135  # default_proto
ELEM_DEFAULT_SYMBOLS = 136  # default_symbols
ELEM_EVAL_CALLED_PROTOTYPE = 137  # eval_called_prototype
ELEM_EVAL_CURRENT_PROTOTYPE = 138  # eval_current_prototype
ELEM_EXPERIMENTAL_RULES = 139  # experimental_rules
ELEM_FLOWOVERRIDELIST = 140  # flowoverridelist
ELEM_FUNCPTR = 141  # funcptr
ELEM_GLOBAL = 142  # global
ELEM_INCIDENTALCOPY = 143  # incidentalcopy
ELEM_INFERPTRBOUNDS = 144  # inferptrbounds
ELEM_MODELALIAS = 145  # modelalias
ELEM_NOHIGHPTR = 146  # nohighptr
ELEM_PROCESSOR_SPEC = 147  # processor_spec
ELEM_PROGRAMCOUNTER = 148  # programcounter
ELEM_PROPERTIES = 149  # properties
ELEM_PROPERTY = 150  # property
ELEM_READONLY = 151  # readonly
ELEM_REGISTER_DATA = 152  # register_data
ELEM_RULE = 153  # rule
ELEM_SAVE_STATE = 154  # save_state
ELEM_SEGMENTED_ADDRESS = 155  # segmented_address
ELEM_SPACEBASE = 156  # spacebase
ELEM_SPECEXTENSIONS = 157  # specextensions
ELEM_STACKPOINTER = 158  # stackpointer
ELEM_VOLATILE = 159  # volatile
ELEM_GROUP = 160  # group
ELEM_INTERNALLIST = 161  # internallist
ELEM_KILLEDBYCALL = 162  # killedbycall
ELEM_LIKELYTRASH = 163  # likelytrash
ELEM_LOCALRANGE = 164  # localrange
ELEM_MODEL = 165  # model
ELEM_PARAM = 166  # param
ELEM_PARAMRANGE = 167  # paramrange
ELEM_PENTRY = 168  # pentry
ELEM_PROTOTYPE = 169  # prototype
ELEM_RESOLVEPROTOTYPE = 170  # resolveprototype
ELEM_RETPARAM = 171  # retparam
ELEM_RETURNSYM = 172  # returnsym
ELEM_UNAFFECTED = 173  # unaffected
ELEM_INTERNAL_STORAGE = 286  # internal_storage
ELEM_ALIASBLOCK = 174  # aliasblock
ELEM_ALLOWCONTEXTSET = 175  # allowcontextset
ELEM_ANALYZEFORLOOPS = 176  # analyzeforloops
ELEM_COMMENTHEADER = 177  # commentheader
ELEM_COMMENTINDENT = 178  # commentindent
ELEM_COMMENTINSTRUCTION = 179  # commentinstruction
ELEM_COMMENTSTYLE = 180  # commentstyle
ELEM_CONVENTIONPRINTING = 181  # conventionprinting
ELEM_CURRENTACTION = 182  # currentaction
ELEM_DEFAULTPROTOTYPE = 183  # defaultprototype
ELEM_ERRORREINTERPRETED = 184  # errorreinterpreted
ELEM_ERRORTOOMANYINSTRUCTIONS = 185  # errortoomanyinstructions
ELEM_ERRORUNIMPLEMENTED = 186  # errorunimplemented
ELEM_BADDATACOUNT = 290  # baddatacount
ELEM_EXTRAPOP = 187  # extrapop
ELEM_IGNOREUNIMPLEMENTED = 188  # ignoreunimplemented
ELEM_INDENTINCREMENT = 189  # indentincrement
ELEM_INFERCONSTPTR = 190  # inferconstptr
ELEM_INLINE = 191  # inline
ELEM_INPLACEOPS = 192  # inplaceops
ELEM_INTEGERFORMAT = 193  # integerformat
ELEM_JUMPLOAD = 194  # jumpload
ELEM_MAXINSTRUCTION = 195  # maxinstruction
ELEM_MAXLINEWIDTH = 196  # maxlinewidth
ELEM_NAMESPACESTRATEGY = 197  # namespacestrategy
ELEM_NOCASTPRINTING = 198  # nocastprinting
ELEM_NORETURN = 199  # noreturn
ELEM_NULLPRINTING = 200  # nullprinting
ELEM_OPTIONSLIST = 201  # optionslist
ELEM_PARAM1 = 202  # param1
ELEM_PARAM2 = 203  # param2
ELEM_PARAM3 = 204  # param3
ELEM_PROTOEVAL = 205  # protoeval
ELEM_SETACTION = 206  # setaction
ELEM_SETLANGUAGE = 207  # setlanguage
ELEM_STRUCTALIGN = 208  # structalign
ELEM_TOGGLERULE = 209  # togglerule
ELEM_WARNING = 210  # warning
ELEM_BRACEFORMAT = 284  # braceformat
ELEM_BASICOVERRIDE = 211  # basicoverride
ELEM_DEST = 212  # dest
ELEM_JUMPTABLE = 213  # jumptable
ELEM_LOADTABLE = 214  # loadtable
ELEM_NORMADDR = 215  # normaddr
ELEM_NORMHASH = 216  # normhash
ELEM_STARTVAL = 217  # startval
ELEM_DEADCODEDELAY = 218  # deadcodedelay
ELEM_FLOW = 219  # flow
ELEM_FORCEGOTO = 220  # forcegoto
ELEM_CALLDEST = 221  # calldest
ELEM_MULTISTAGEJUMP = 222  # multistagejump
ELEM_OVERRIDE = 223  # override
ELEM_PROTOOVERRIDE = 224  # protooverride
ELEM_PREFERSPLIT = 225  # prefersplit
ELEM_CALLGRAPH = 226  # callgraph
ELEM_NODE = 227  # node
ELEM_LOCALDB = 228  # localdb
ELEM_DOC = 229  # doc
ELEM_BINARYIMAGE = 230  # binaryimage
ELEM_BYTECHUNK = 231  # bytechunk
ELEM_COMPILER = 232  # compiler
ELEM_DESCRIPTION = 233  # description
ELEM_LANGUAGE = 234  # language
ELEM_XML_SAVEFILE = 236  # xml_savefile
ELEM_RAW_SAVEFILE = 237  # raw_savefile
ELEM_COMMAND_ISNAMEUSED = 239  # command_isnameused
ELEM_COMMAND_GETBYTES = 240  # command_getbytes
ELEM_COMMAND_GETCALLFIXUP = 241  # command_getcallfixup
ELEM_COMMAND_GETCALLMECH = 242  # command_getcallmech
ELEM_COMMAND_GETCALLOTHERFIXUP = 243  # command_getcallotherfixup
ELEM_COMMAND_GETCODELABEL = 244  # command_getcodelabel
ELEM_COMMAND_GETCOMMENTS = 245  # command_getcomments
ELEM_COMMAND_GETCPOOLREF = 246  # command_getcpoolref
ELEM_COMMAND_GETDATATYPE = 247  # command_getdatatype
ELEM_COMMAND_GETEXTERNALREF = 248  # command_getexternalref
ELEM_COMMAND_GETMAPPEDSYMBOLS = 249  # command_getmappedsymbols
ELEM_COMMAND_GETNAMESPACEPATH = 250  # command_getnamespacepath
ELEM_COMMAND_GETPCODE = 251  # command_getpcode
ELEM_COMMAND_GETPCODEEXECUTABLE = 252  # command_getpcodeexecutable
ELEM_COMMAND_GETREGISTER = 253  # command_getregister
ELEM_COMMAND_GETREGISTERNAME = 254  # command_getregistername
ELEM_COMMAND_GETSTRINGDATA = 255  # command_getstring
ELEM_COMMAND_GETTRACKEDREGISTERS = 256  # command_gettrackedregisters
ELEM_COMMAND_GETUSEROPNAME = 257  # command_getuseropname
ELEM_BLOCKSIG = 258  # blocksig
ELEM_CALL = 259  # call
ELEM_GENSIG = 260  # gensig
ELEM_MAJOR = 261  # major
ELEM_MINOR = 262  # minor
ELEM_COPYSIG = 263  # copysig
ELEM_SETTINGS = 264  # settings
ELEM_SIG = 265  # sig
ELEM_SIGNATUREDESC = 266  # signaturedesc
ELEM_SIGNATURES = 267  # signatures
ELEM_SIGSETTINGS = 268  # sigsettings
ELEM_VARSIG = 269  # varsig
ELEM_SPLITDATATYPE = 270  # splitdatatype
ELEM_JUMPTABLEMAX = 271  # jumptablemax
ELEM_NANIGNORE = 272  # nanignore
ELEM_DATATYPE = 273  # datatype
ELEM_CONSUME = 274  # consume
ELEM_CONSUME_EXTRA = 275  # consume_extra
ELEM_CONVERT_TO_PTR = 276  # convert_to_ptr
ELEM_GOTO_STACK = 277  # goto_stack
ELEM_JOIN = 278  # join
ELEM_DATATYPE_AT = 279  # datatype_at
ELEM_POSITION = 280  # position
ELEM_VARARGS = 281  # varargs
ELEM_HIDDEN_RETURN = 282  # hidden_return
ELEM_JOIN_PER_PRIMITIVE = 283  # join_per_primitive
ELEM_JOIN_DUAL_CLASS = 285  # join_dual_class
ELEM_EXTRA_STACK = 287  # extra_stack
ELEM_CONSUME_REMAINING = 288  # consume_remaining
ELEM_UNKNOWN = 291  # XMLunknown

ATTRIB_CONTENT = 1  # XMLcontent
ATTRIB_ALIGN = 2  # align
ATTRIB_BIGENDIAN = 3  # bigendian
ATTRIB_CONSTRUCTOR = 4  # constructor
ATTRIB_DESTRUCTOR = 5  # destructor
ATTRIB_EXTRAPOP = 6  # extrapop
ATTRIB_FORMAT = 7  # format
ATTRIB_HIDDENRETPARM = 8  # hiddenretparm
ATTRIB_ID = 9  # id
ATTRIB_INDEX = 10  # index
ATTRIB_INDIRECTSTORAGE = 11  # indirectstorage
ATTRIB_METATYPE = 12  # metatype
ATTRIB_MODEL = 13  # model
ATTRIB_NAME = 14  # name
ATTRIB_NAMELOCK = 15  # namelock
ATTRIB_OFFSET = 16  # offset
ATTRIB_READONLY = 17  # readonly
ATTRIB_REF = 18  # ref
ATTRIB_SIZE = 19  # size
ATTRIB_SPACE = 20  # space
ATTRIB_THISPTR = 21  # thisptr
ATTRIB_TYPE = 22  # type
ATTRIB_TYPELOCK = 23  # typelock
ATTRIB_VAL = 24  # val
ATTRIB_VALUE = 25  # value
ATTRIB_WORDSIZE = 26  # wordsize
ATTRIB_FIRST = 27  # first
ATTRIB_LAST = 28  # last
ATTRIB_UNIQ = 29  # uniq
ATTRIB_ADDRTIED = 30  # addrtied
ATTRIB_GRP = 31  # grp
ATTRIB_INPUT = 32  # input
ATTRIB_PERSISTS = 33  # persists
ATTRIB_UNAFF = 34  # unaff
ATTRIB_BLOCKREF = 35  # blockref
ATTRIB_CLOSE = 36  # close
ATTRIB_COLOR = 37  # color
ATTRIB_INDENT = 38  # indent
ATTRIB_OFF = 39  # off
ATTRIB_OPEN = 40  # open
ATTRIB_OPREF = 41  # opref
ATTRIB_VARREF = 42  # varref
ATTRIB_CODE = 43  # code
ATTRIB_CONTAIN = 44  # contain
ATTRIB_DEFAULTSPACE = 45  # defaultspace
ATTRIB_UNIQBASE = 46  # uniqbase
ATTRIB_ALIGNMENT = 47  # alignment
ATTRIB_ARRAYSIZE = 48  # arraysize
ATTRIB_CHAR = 49  # char
ATTRIB_CORE = 50  # core
ATTRIB_ENUM = 51  # enum
ATTRIB_INCOMPLETE = 52  # incomplete
ATTRIB_ENUMSIZE = 53  # enumsize
ATTRIB_INTSIZE = 54  # intsize
ATTRIB_LONGSIZE = 55  # longsize
ATTRIB_OPAQUESTRING = 56  # opaquestring
ATTRIB_SIGNED = 57  # signed
ATTRIB_STRUCTALIGN = 58  # structalign
ATTRIB_UTF = 59  # utf
ATTRIB_VARLENGTH = 60  # varlength
ATTRIB_CAT = 61  # cat
ATTRIB_FIELD = 62  # field
ATTRIB_MERGE = 63  # merge
ATTRIB_SCOPEIDBYNAME = 64  # scopeidbyname
ATTRIB_VOLATILE = 65  # volatile
ATTRIB_CLASS = 66  # class
ATTRIB_REPREF = 67  # repref
ATTRIB_SYMREF = 68  # symref
ATTRIB_TRUNC = 69  # trunc
ATTRIB_DYNAMIC = 70  # dynamic
ATTRIB_INCIDENTALCOPY = 71  # incidentalcopy
ATTRIB_INJECT = 72  # inject
ATTRIB_PARAMSHIFT = 73  # paramshift
ATTRIB_TARGETOP = 74  # targetop
ATTRIB_ALTINDEX = 75  # altindex
ATTRIB_DEPTH = 76  # depth
ATTRIB_END = 77  # end
ATTRIB_OPCODE = 78  # opcode
ATTRIB_REV = 79  # rev
ATTRIB_A = 80  # a
ATTRIB_B = 81  # b
ATTRIB_LENGTH = 82  # length
ATTRIB_TAG = 83  # tag
ATTRIB_NOCODE = 84  # nocode
ATTRIB_FARPOINTER = 85  # farpointer
ATTRIB_INPUTOP = 86  # inputop
ATTRIB_OUTPUTOP = 87  # outputop
ATTRIB_USEROP = 88  # userop
ATTRIB_BASE = 89  # base
ATTRIB_DEADCODEDELAY = 90  # deadcodedelay
ATTRIB_DELAY = 91  # delay
ATTRIB_LOGICALSIZE = 92  # logicalsize
ATTRIB_PHYSICAL = 93  # physical
ATTRIB_PIECE = 94  # piece
ATTRIB_ADJUSTVMA = 103  # adjustvma
ATTRIB_ENABLE = 104  # enable
ATTRIB_GROUP = 105  # group
ATTRIB_GROWTH = 106  # growth
ATTRIB_KEY = 107  # key
ATTRIB_LOADERSYMBOLS = 108  # loadersymbols
ATTRIB_PARENT = 109  # parent
ATTRIB_REGISTER = 110  # register
ATTRIB_REVERSEJUSTIFY = 111  # reversejustify
ATTRIB_SIGNEXT = 112  # signext
ATTRIB_STYLE = 113  # style
ATTRIB_CUSTOM = 114  # custom
ATTRIB_DOTDOTDOT = 115  # dotdotdot
ATTRIB_EXTENSION = 116  # extension
ATTRIB_HASTHIS = 117  # hasthis
ATTRIB_INLINE = 118  # inline
ATTRIB_KILLEDBYCALL = 119  # killedbycall
ATTRIB_MAXSIZE = 120  # maxsize
ATTRIB_MINSIZE = 121  # minsize
ATTRIB_MODELLOCK = 122  # modellock
ATTRIB_NORETURN = 123  # noreturn
ATTRIB_POINTERMAX = 124  # pointermax
ATTRIB_SEPARATEFLOAT = 125  # separatefloat
ATTRIB_STACKSHIFT = 126  # stackshift
ATTRIB_STRATEGY = 127  # strategy
ATTRIB_THISBEFORERETPOINTER = 128  # thisbeforeretpointer
ATTRIB_VOIDLOCK = 129  # voidlock
ATTRIB_VECTOR_LANE_SIZES = 130  # vector_lane_sizes
ATTRIB_LABEL = 131  # label
ATTRIB_NUM = 132  # num
ATTRIB_LOCK = 133  # lock
ATTRIB_MAIN = 134  # main
ATTRIB_ARCH = 135  # arch
ATTRIB_DEPRECATED = 136  # deprecated
ATTRIB_ENDIAN = 137  # endian
ATTRIB_PROCESSOR = 138  # processor
ATTRIB_PROCESSORSPEC = 139  # processorspec
ATTRIB_SLAFILE = 140  # slafile
ATTRIB_SPEC = 141  # spec
ATTRIB_TARGET = 142  # target
ATTRIB_VARIANT = 143  # variant
ATTRIB_VERSION = 144  # version
ATTRIB_BADDATA = 145  # baddata
ATTRIB_HASH = 146  # hash
ATTRIB_UNIMPL = 147  # unimpl
ATTRIB_ADDRESS = 148  # address
ATTRIB_STORAGE = 149  # storage
ATTRIB_STACKSPILL = 150  # stackspill
ATTRIB_SIZES = 151  # sizes
ATTRIB_BACKFILL = 152  # backfill
ATTRIB_MAX_PRIMITIVES = 153  # maxprimitives
ATTRIB_REVERSESIGNIF = 154  # reversesignif
ATTRIB_MATCHSIZE = 155  # matchsize
ATTRIB_AFTER_BYTES = 156  # afterbytes
ATTRIB_AFTER_STORAGE = 157  # afterstorage
ATTRIB_FILL_ALTERNATE = 158  # fillalternate
ATTRIB_UNKNOWN = 159  # XMLunknown

ELEMENT_NAMES = {
    1: 'data',
    2: 'input',
    3: 'off',
    4: 'output',
    5: 'returnaddress',
    6: 'symbol',
    7: 'target',
    8: 'val',
    9: 'value',
    10: 'void',
    11: 'addr',
    12: 'range',
    13: 'rangelist',
    14: 'register',
    15: 'seqnum',
    16: 'varnode',
    17: 'break',
    18: 'clang_document',
    19: 'funcname',
    20: 'funcproto',
    21: 'label',
    22: 'return_type',
    23: 'statement',
    24: 'syntax',
    25: 'vardecl',
    26: 'variable',
    27: 'op',
    28: 'sleigh',
    29: 'space',
    30: 'spaceid',
    31: 'spaces',
    32: 'space_base',
    33: 'space_other',
    34: 'space_overlay',
    35: 'space_unique',
    36: 'truncate_space',
    37: 'absolute_max_alignment',
    38: 'bitfield_packing',
    39: 'char_size',
    40: 'char_type',
    41: 'coretypes',
    42: 'data_organization',
    43: 'def',
    44: 'default_alignment',
    45: 'default_pointer_alignment',
    46: 'double_size',
    47: 'entry',
    48: 'enum',
    49: 'field',
    50: 'float_size',
    51: 'integer_size',
    52: 'long_double_size',
    53: 'long_long_size',
    54: 'long_size',
    55: 'machine_alignment',
    56: 'pointer_shift',
    57: 'pointer_size',
    58: 'short_size',
    59: 'size_alignment_map',
    60: 'type',
    61: 'type_alignment_enabled',
    62: 'typegrp',
    63: 'typeref',
    64: 'use_MS_convention',
    65: 'wchar_size',
    66: 'zero_length_boundary',
    67: 'collision',
    68: 'db',
    69: 'equatesymbol',
    70: 'externrefsymbol',
    71: 'facetsymbol',
    72: 'functionshell',
    73: 'hash',
    74: 'hole',
    75: 'labelsym',
    76: 'mapsym',
    77: 'parent',
    78: 'property_changepoint',
    79: 'rangeequalssymbols',
    80: 'scope',
    81: 'symbollist',
    82: 'high',
    83: 'bytes',
    84: 'string',
    85: 'stringmanage',
    86: 'comment',
    87: 'commentdb',
    88: 'text',
    89: 'addr_pcode',
    90: 'body',
    91: 'callfixup',
    92: 'callotherfixup',
    93: 'case_pcode',
    94: 'context',
    95: 'default_pcode',
    96: 'inject',
    97: 'injectdebug',
    98: 'inst',
    99: 'payload',
    100: 'pcode',
    101: 'size_pcode',
    102: 'bhead',
    103: 'block',
    104: 'blockedge',
    105: 'edge',
    106: 'parammeasures',
    107: 'proto',
    108: 'rank',
    109: 'constantpool',
    110: 'cpoolrec',
    111: 'ref',
    112: 'token',
    113: 'iop',
    114: 'unimpl',
    115: 'ast',
    116: 'function',
    117: 'highlist',
    118: 'jumptablelist',
    119: 'varnodes',
    120: 'context_data',
    121: 'context_points',
    122: 'context_pointset',
    123: 'context_set',
    124: 'set',
    125: 'tracked_pointset',
    126: 'tracked_set',
    127: 'constresolve',
    128: 'jumpassist',
    129: 'segmentop',
    130: 'address_shift_amount',
    131: 'aggressivetrim',
    132: 'compiler_spec',
    133: 'data_space',
    134: 'default_memory_blocks',
    135: 'default_proto',
    136: 'default_symbols',
    137: 'eval_called_prototype',
    138: 'eval_current_prototype',
    139: 'experimental_rules',
    140: 'flowoverridelist',
    141: 'funcptr',
    142: 'global',
    143: 'incidentalcopy',
    144: 'inferptrbounds',
    145: 'modelalias',
    146: 'nohighptr',
    147: 'processor_spec',
    148: 'programcounter',
    149: 'properties',
    150: 'property',
    151: 'readonly',
    152: 'register_data',
    153: 'rule',
    154: 'save_state',
    155: 'segmented_address',
    156: 'spacebase',
    157: 'specextensions',
    158: 'stackpointer',
    159: 'volatile',
    160: 'group',
    161: 'internallist',
    162: 'killedbycall',
    163: 'likelytrash',
    164: 'localrange',
    165: 'model',
    166: 'param',
    167: 'paramrange',
    168: 'pentry',
    169: 'prototype',
    170: 'resolveprototype',
    171: 'retparam',
    172: 'returnsym',
    173: 'unaffected',
    174: 'aliasblock',
    175: 'allowcontextset',
    176: 'analyzeforloops',
    177: 'commentheader',
    178: 'commentindent',
    179: 'commentinstruction',
    180: 'commentstyle',
    181: 'conventionprinting',
    182: 'currentaction',
    183: 'defaultprototype',
    184: 'errorreinterpreted',
    185: 'errortoomanyinstructions',
    186: 'errorunimplemented',
    187: 'extrapop',
    188: 'ignoreunimplemented',
    189: 'indentincrement',
    190: 'inferconstptr',
    191: 'inline',
    192: 'inplaceops',
    193: 'integerformat',
    194: 'jumpload',
    195: 'maxinstruction',
    196: 'maxlinewidth',
    197: 'namespacestrategy',
    198: 'nocastprinting',
    199: 'noreturn',
    200: 'nullprinting',
    201: 'optionslist',
    202: 'param1',
    203: 'param2',
    204: 'param3',
    205: 'protoeval',
    206: 'setaction',
    207: 'setlanguage',
    208: 'structalign',
    209: 'togglerule',
    210: 'warning',
    211: 'basicoverride',
    212: 'dest',
    213: 'jumptable',
    214: 'loadtable',
    215: 'normaddr',
    216: 'normhash',
    217: 'startval',
    218: 'deadcodedelay',
    219: 'flow',
    220: 'forcegoto',
    221: 'calldest',
    222: 'multistagejump',
    223: 'override',
    224: 'protooverride',
    225: 'prefersplit',
    226: 'callgraph',
    227: 'node',
    228: 'localdb',
    229: 'doc',
    230: 'binaryimage',
    231: 'bytechunk',
    232: 'compiler',
    233: 'description',
    234: 'language',
    236: 'xml_savefile',
    237: 'raw_savefile',
    239: 'command_isnameused',
    240: 'command_getbytes',
    241: 'command_getcallfixup',
    242: 'command_getcallmech',
    243: 'command_getcallotherfixup',
    244: 'command_getcodelabel',
    245: 'command_getcomments',
    246: 'command_getcpoolref',
    247: 'command_getdatatype',
    248: 'command_getexternalref',
    249: 'command_getmappedsymbols',
    250: 'command_getnamespacepath',
    251: 'command_getpcode',
    252: 'command_getpcodeexecutable',
    253: 'command_getregister',
    254: 'command_getregistername',
    255: 'command_getstring',
    256: 'command_gettrackedregisters',
    257: 'command_getuseropname',
    258: 'blocksig',
    259: 'call',
    260: 'gensig',
    261: 'major',
    262: 'minor',
    263: 'copysig',
    264: 'settings',
    265: 'sig',
    266: 'signaturedesc',
    267: 'signatures',
    268: 'sigsettings',
    269: 'varsig',
    270: 'splitdatatype',
    271: 'jumptablemax',
    272: 'nanignore',
    273: 'datatype',
    274: 'consume',
    275: 'consume_extra',
    276: 'convert_to_ptr',
    277: 'goto_stack',
    278: 'join',
    279: 'datatype_at',
    280: 'position',
    281: 'varargs',
    282: 'hidden_return',
    283: 'join_per_primitive',
    284: 'braceformat',
    285: 'join_dual_class',
    286: 'internal_storage',
    287: 'extra_stack',
    288: 'consume_remaining',
    289: 'bitfield',
    290: 'baddatacount',
    291: 'XMLunknown',
}

ATTRIBUTE_NAMES = {
    1: 'XMLcontent',
    2: 'align',
    3: 'bigendian',
    4: 'constructor',
    5: 'destructor',
    6: 'extrapop',
    7: 'format',
    8: 'hiddenretparm',
    9: 'id',
    10: 'index',
    11: 'indirectstorage',
    12: 'metatype',
    13: 'model',
    14: 'name',
    15: 'namelock',
    16: 'offset',
    17: 'readonly',
    18: 'ref',
    19: 'size',
    20: 'space',
    21: 'thisptr',
    22: 'type',
    23: 'typelock',
    24: 'val',
    25: 'value',
    26: 'wordsize',
    27: 'first',
    28: 'last',
    29: 'uniq',
    30: 'addrtied',
    31: 'grp',
    32: 'input',
    33: 'persists',
    34: 'unaff',
    35: 'blockref',
    36: 'close',
    37: 'color',
    38: 'indent',
    39: 'off',
    40: 'open',
    41: 'opref',
    42: 'varref',
    43: 'code',
    44: 'contain',
    45: 'defaultspace',
    46: 'uniqbase',
    47: 'alignment',
    48: 'arraysize',
    49: 'char',
    50: 'core',
    51: 'enum',
    52: 'incomplete',
    53: 'enumsize',
    54: 'intsize',
    55: 'longsize',
    56: 'opaquestring',
    57: 'signed',
    58: 'structalign',
    59: 'utf',
    60: 'varlength',
    61: 'cat',
    62: 'field',
    63: 'merge',
    64: 'scopeidbyname',
    65: 'volatile',
    66: 'class',
    67: 'repref',
    68: 'symref',
    69: 'trunc',
    70: 'dynamic',
    71: 'incidentalcopy',
    72: 'inject',
    73: 'paramshift',
    74: 'targetop',
    75: 'altindex',
    76: 'depth',
    77: 'end',
    78: 'opcode',
    79: 'rev',
    80: 'a',
    81: 'b',
    82: 'length',
    83: 'tag',
    84: 'nocode',
    85: 'farpointer',
    86: 'inputop',
    87: 'outputop',
    88: 'userop',
    89: 'base',
    90: 'deadcodedelay',
    91: 'delay',
    92: 'logicalsize',
    93: 'physical',
    94: 'piece',
    103: 'adjustvma',
    104: 'enable',
    105: 'group',
    106: 'growth',
    107: 'key',
    108: 'loadersymbols',
    109: 'parent',
    110: 'register',
    111: 'reversejustify',
    112: 'signext',
    113: 'style',
    114: 'custom',
    115: 'dotdotdot',
    116: 'extension',
    117: 'hasthis',
    118: 'inline',
    119: 'killedbycall',
    120: 'maxsize',
    121: 'minsize',
    122: 'modellock',
    123: 'noreturn',
    124: 'pointermax',
    125: 'separatefloat',
    126: 'stackshift',
    127: 'strategy',
    128: 'thisbeforeretpointer',
    129: 'voidlock',
    130: 'vector_lane_sizes',
    131: 'label',
    132: 'num',
    133: 'lock',
    134: 'main',
    135: 'arch',
    136: 'deprecated',
    137: 'endian',
    138: 'processor',
    139: 'processorspec',
    140: 'slafile',
    141: 'spec',
    142: 'target',
    143: 'variant',
    144: 'version',
    145: 'baddata',
    146: 'hash',
    147: 'unimpl',
    148: 'address',
    149: 'storage',
    150: 'stackspill',
    151: 'sizes',
    152: 'backfill',
    153: 'maxprimitives',
    154: 'reversesignif',
    155: 'matchsize',
    156: 'afterbytes',
    157: 'afterstorage',
    158: 'fillalternate',
    159: 'XMLunknown',
}
