"""Generate element/attribute id tables from Ghidra's Java sources.

Usage: python scripts/gen_id_tables.py /path/to/ghidra > angr_ghidra_core/ghidra_wire/ids.py
"""

from __future__ import annotations

import re
import sys

PCODE_DIR = "Ghidra/Framework/SoftwareModeling/src/main/java/ghidra/program/model/pcode"

ELEM_RE = re.compile(
    r"public static final ElementId (\w+) = new ElementId\(\"([^\"]+)\", (\w+)\)"
)
ATTRIB_RE = re.compile(
    r"public static final AttributeId (\w+) = new AttributeId\(\"([^\"]+)\", (\w+)\)"
)
INT_RE = re.compile(r"public static final int (\w+) = (\d+);")


def main() -> None:
    ghidra_root = sys.argv[1]
    elem_src = " ".join(open(f"{ghidra_root}/{PCODE_DIR}/ElementId.java").read().split())
    attrib_src = " ".join(open(f"{ghidra_root}/{PCODE_DIR}/AttributeId.java").read().split())

    consts = dict(INT_RE.findall(elem_src) + INT_RE.findall(attrib_src))

    def resolve(triples):
        return [(c, n, v if v.isdigit() else consts[v]) for c, n, v in triples]

    elems = resolve(ELEM_RE.findall(elem_src))
    attribs = resolve(ATTRIB_RE.findall(attrib_src))

    print('"""Element/attribute id tables. GENERATED by scripts/gen_id_tables.py — do not edit."""')
    print()
    print("# Ghidra 12.2 vocabulary from ElementId.java / AttributeId.java")
    print()
    for const, name, num in elems:
        print(f"{const} = {num}  # {name}")
    print()
    for const, name, num in attribs:
        print(f"{const} = {num}  # {name}")
    print()
    print("ELEMENT_NAMES = {")
    for const, name, num in sorted(elems, key=lambda t: int(t[2])):
        print(f"    {num}: {name!r},")
    print("}")
    print()
    print("ATTRIBUTE_NAMES = {")
    for const, name, num in sorted(attribs, key=lambda t: int(t[2])):
        print(f"    {num}: {name!r},")
    print("}")


if __name__ == "__main__":
    main()
